### PR TITLE
Flaky test fixed

### LINKED ISSUE #10: Fix Flaky Test
When running test by `cargo test` we get result from test
```
test dictionary::tests::test_serialize_save_read ... FAILED
```
and sometimes
```
test dictionary::tests::test_serialize_save_read ... ok
```

### PR DESCRIPTION
**Pull request by macieknajbar**

### CODE REVIEW

File: src/dictionary/mod.rs [hunk 1]
```diff
@@ -252,35 +254,26 @@ mod tests {
...
-        let buffer = serialize.serialize(TEXT);
-        if let Err(_) = serialize.save_schema_to_file(PATH) {
-            assert!(false);
-        }
-        let mock1 = MyFilterMock::new();
-        let Ok(new_serializer) = Module::read_schema_from_file(PATH, mock1) else {
-            assert!(false);
-            return;
-        };
+        let actual = Module::read_schema_from_file(path, MyFilterMock::new())?;
```
Comment (macieknajbar) [inline src/dictionary/mod.rs:262]: IMO readability is more important in tests than safety. Let me know what you think.

File: src/dictionary/mod.rs [hunk 2]
```diff
@@ -307,7 +300,7 @@ mod tests {
 
         let mut serialize = Module::new(mock);
         let buffer = serialize.serialize(TEXT);
-        if let Err(_) = serialize.save_schema_to_file(PATH) {
+        if let Err(_) = serialize.save_schema_to_file(path) {
```
Comment (macieknajbar) [inline src/dictionary/mod.rs:303]: Tests are run parallelly and this test was  writing to file that the previous test was reading from.

**Review by bartossh — APPROVED** [review]
Looks good! 🚀
